name: Wine Cube Tours
favicon: null
layout_spectrum: 0.26771182497031987
typography_spectrum: 0.827659975271672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6387991267256439
  lightness: 0.6825382297392935
  saturation: 0.11293485388159752
  rhythmicContrast: 0.3210573873948306
purpose: []
