name: Wine Cube Tours
favicon: null
layout_spectrum: 0.26771182497031987
typography_spectrum: 0.827659975271672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#36b8ba'
    - '#d06424'
    - '#9a1b1e'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
